name: ChronoMini
on:
    push:
      branches:
        - "main"
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tests-api
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Create test env file
      run: cp ../ChronoMini/.env.example ../ChronoMini/.env.test
    - name: Create docker env file
      run: echo "MYSQL_ROOT_PASSWORD=testpassword" > ../.env
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm run test
  build-and-push-image-chronomini-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create prod env file
        run: |
          cat <<EOF > ./ChronoMini/.env.prod
          APP_NAME=ChronoMini
          APP_ENV=production
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_TIMEZONE=Europe/Paris
          APP_URL=https://api.chronomini.fr
          APP_LOCALE=fr
          APP_FALLBACK_LOCALE=fr
          APP_FAKER_LOCALE=fr_FR
          APP_MAINTENANCE_DRIVER=file
          BCRYPT_ROUNDS=12
          LOG_CHANNEL=stack
          LOG_STACK=single
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=warning
          DB_CONNECTION=mysql
          DB_HOST=mysql_db
          DB_PORT=3306
          DB_DATABASE=chronomini
          DB_USERNAME=root
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          SESSION_DRIVER=database
          SESSION_LIFETIME=120
          SESSION_ENCRYPT=true
          SESSION_PATH=/
          SESSION_DOMAIN=.chronomini.fr
          SANCTUM_STATEFUL_DOMAINS=chronomini.fr,api.chronomini.fr
          BROADCAST_CONNECTION=log
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=database
          CACHE_STORE=database
          CACHE_PREFIX=
          MAIL_MAILER=smtp
          MAIL_HOST=smtp.hostinger.com
          MAIL_PORT=465
          MAIL_USERNAME=noreply@chronomini.fr
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          MAIL_ENCRYPTION=ssl
          MAIL_FROM_ADDRESS="noreply@chronomini.fr"
          MAIL_FROM_NAME=ChronoMini
          FRONTEND_URL=https://chronomini.fr
          ADMIN_FIRST_NAME=César
          ADMIN_LAST_NAME=Vidal
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          ADMIN_EMAIL=admin@jp.fr
          VITE_APP_NAME=ChronoMini
          EOF
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: jpdwwm
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ChronoMini
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/jpdwwm/chronomini-prod:latest
            ghcr.io/jpdwwm/chronomini-prod:${{ github.sha }}
  build-and-push-image-chronomini-front-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create front prod env file
        run: echo 'VITE_API_BASE=https://api.chronomini.fr' > ./ChronoMini-front/.env.prod
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: jpdwwm
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ChronoMini-front
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/jpdwwm/chronomini-front-prod:latest
            ghcr.io/jpdwwm/chronomini-front-prod:${{ github.sha }}
