name: ChronoMini
on:
    push:
      branches:
        - "main"
permissions:
  contents: read
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tests-api
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create test env file
      run: cp ../ChronoMini/.env.example ../ChronoMini/.env.test
    - name: Create docker env file
      run: echo "MYSQL_ROOT_PASSWORD=testpassword" > ../.env
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Wait for database to be ready
      run: |
        for i in $(seq 1 30); do
          docker exec laravel-docker bash -c "php artisan db:monitor" && break
          sleep 2
        done
      shell: bash
    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm run test
  build-and-push-image-chronomini-prod:
    needs:
      - tests
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ChronoMini
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/jpdwwm/chronomini-prod:latest
            ghcr.io/jpdwwm/chronomini-prod:${{ github.sha }}
  build-and-push-image-chronomini-front-prod:
    needs:
      - tests
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create front prod env file
        run: echo 'VITE_API_BASE=https://api.chronomini.fr' > ./ChronoMini-front/.env.prod
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ChronoMini-front
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/jpdwwm/chronomini-front-prod:latest
            ghcr.io/jpdwwm/chronomini-front-prod:${{ github.sha }}
